workflows:
  cordova-workflow:
    name: Cordova Android Build
    max_build_duration: 60
    environment:
      vars:
        CORDOVA_PLATFORM: android
      node: latest
      java: 11
    scripts:
      - name: Install Cordova CLI
        script: npm install -g cordova

      - name: Install dependencies
        script: npm install

      - name: Add Android platform
        script: cordova platform add android

      - name: Add Cordova Plugins
        script: |
          cordova plugin add cordova-plugin-background-mode
          cordova plugin add cordova-plugin-geolocation
          cordova plugin add cordova-plugin-media
          cordova plugin add cordova-plugin-file
          cordova plugin add cordova-plugin-whitelist

      - name: Build APK
        script: cordova build android --release

    artifacts:
      - platforms/android/app/build/outputs/**/*.apk

    publishing:
      email:
        recipients:
          - your-email@example.com
