workflows:
  cordova-workflow:
    name: Cordova Android Build
    max_build_duration: 60
    environment:
      vars:
        CORDOVA_PLATFORM: android
        ANDROID_HOME: /usr/local/share/android-sdk
      java: 17
      node: latest

    scripts:
      - name: Install Cordova CLI
        script: |
          npm install -g cordova

      - name: Install dependencies
        script: |
          npm install

      - name: Install Android Build Tools 34.0.0
        script: |
          yes | sdkmanager --licenses
          sdkmanager "build-tools;34.0.0" "platforms;android-34"

      - name: Add Android platform
        script: |
          cordova platform add android

      - name: Build APK
        script: |
          export JAVA_HOME=$(/usr/libexec/java_home -v 17)
          cordova build android --release --no-interactive --verbose

    artifacts:
      - platforms/android/app/build/outputs/**/*.apk

    publishing:
      email:
        recipients:
          - your-email@example.com
