workflows:
  cordova-workflow:
    name: Cordova Android Build
    max_build_duration: 60
    environment:
      vars:
        CORDOVA_PLATFORM: android
      node: latest
      java: 17  # ✅ Use Java 17 as required by Android Gradle Plugin

    scripts:
      - name: Install Cordova CLI
        script: npm install -g cordova

      - name: Install dependencies
        script: npm install

      - name: Install Android Build Tools 34.0.0
        script: |
          echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "build-tools;34.0.0" "platforms;android-34"

      - name: Add Android platform
        script: cordova platform add android

      - name: Add Cordova Plugins
        script: |
          cordova plugin add cordova-plugin-geolocation
          cordova plugin add cordova-plugin-background-mode
          cordova plugin add cordova-plugin-media

      - name: Build APK and AAB
        script: |
          cordova build android --release
          ls -la platforms/android/app/build/outputs/apk/release/
          ls -la platforms/android/app/build/outputs/bundle/release/

    artifacts:
      - platforms/android/app/build/outputs/apk/release/*.apk  # ✅ Collect APKs
      - platforms/android/app/build/outputs/bundle/release/*.aab  # ✅ Collect AABs

    publishing:
      email:
        recipients:
          - your-email@example.com
