workflows:
  cordova-workflow:
    name: Cordova Android Build
    max_build_duration: 60
    environment:
      vars:
        CORDOVA_PLATFORM: android
      node: latest
      java: 11
    scripts:
      - name: Install Cordova CLI
        script: npm install -g cordova
      - name: Install dependencies
        script: npm install
      - name: Add Android platform
        script: cordova platform add android
      - name: Build APK
        script: cordova build android --release
    artifacts:
      - platforms/android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
